// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoLaboratorio25.Data;

#nullable disable

namespace ProjetoLaboratorio25.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512104331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoLaboratorio25.Models.Competicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumEquipas")
                        .HasColumnType("int");

                    b.Property<int>("NumJogadores")
                        .HasColumnType("int");

                    b.Property<int>("PontosEmpate")
                        .HasColumnType("int");

                    b.Property<int>("PontosVitoria")
                        .HasColumnType("int");

                    b.Property<string>("TipoCompeticao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Competicoes");
                });

            modelBuilder.Entity("ProjetoLaboratorio25.Models.ConfiguracaoFase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticaoId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CriteriosDesempate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FaseNumero")
                        .HasColumnType("int");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PontosDerrota")
                        .HasColumnType("int");

                    b.Property<int>("PontosEmpate")
                        .HasColumnType("int");

                    b.Property<int>("PontosVitoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.ToTable("ConfiguracoesFase");
                });

            modelBuilder.Entity("ProjetoLaboratorio25.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtilizadorNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("ProjetoLaboratorio25.Models.ConfiguracaoFase", b =>
                {
                    b.HasOne("ProjetoLaboratorio25.Models.Competicao", "Competicao")
                        .WithMany("ConfiguracoesFase")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");
                });

            modelBuilder.Entity("ProjetoLaboratorio25.Models.Competicao", b =>
                {
                    b.Navigation("ConfiguracoesFase");
                });
#pragma warning restore 612, 618
        }
    }
}
